//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int addressId { get; set; }
        public string addressStreet { get; set; }
        public string addressProv { get; set; }
        public string addressCountry { get; set; }
        public string postal { get; set; }
        public Nullable<int> addressDateId { get; set; }
    }
}
