//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonationProfile
    {
        public int donationProfileId { get; set; }

        [Display(Name = "Profile Message")]
        [Required(ErrorMessage = "Please enter a message for this donor profile")]
        public string donationMessage { get; set; }

        [Display(Name = "Selected Donor")]
        [Required(ErrorMessage = "Please select a donor for this profile")]
        public int donationId { get; set; }
    
        public virtual Donation Donation { get; set; }
    }
}
