//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation()
        {
            this.DonationHonours = new HashSet<DonationHonour>();
            this.DonationProfiles = new HashSet<DonationProfile>();
        }
    
        [Display(Name = "Donor")]
        public int donationsId { get; set; }
        public decimal donationAmount { get; set; }
        public Nullable<int> occurenceId { get; set; }
        public System.DateTime donationDate { get; set; }
        public Nullable<int> donorsId { get; set; }

        [Display(Name = "First name")]
        public string donorFN { get; set; }
        [Display(Name = "Last name")]
        public string donorLN { get; set; }
        public string email { get; set; }
        public string homeNum { get; set; }
        public string workNum { get; set; }
        public string mobileNum { get; set; }
        public string addressStreet { get; set; }
        public string addressProv { get; set; }
        public string addressCountry { get; set; }
        public string postal { get; set; }
        public string addressCity { get; set; }
        public string honorFN { get; set; }
        public string honorLN { get; set; }
        public string company { get; set; }

        public string fullName()
        {
            return this.donorFN + " " + this.donorLN;
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationHonour> DonationHonours { get; set; }
        public virtual DonationOccurence DonationOccurence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationProfile> DonationProfiles { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
