//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalEvent
    {
        public int eventsId { get; set; }
        public string evntName { get; set; }
        public string evntDesc { get; set; }
        public string evntLoc { get; set; }
        public System.DateTime evntDate { get; set; }
        public System.TimeSpan evntTimebg { get; set; }
        public System.TimeSpan evntTimefn { get; set; }
    }
}
