//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnCall
    {
        public int onCallId { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> employeeId { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public Nullable<int> volunteerId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
