//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsRoom
    {
        public int roomId { get; set; }
        public int patientId { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<System.DateTime> exitDate { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
