//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetaByteContext : DbContext
    {
        public PetaByteContext()
            : base("name=PetaByteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressDate> AddressDates { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Addresses1> Addresses1 { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<Cafeteria> Cafeterias { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CustomerOrder> CustomerOrders { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DonationHonour> DonationHonours { get; set; }
        public virtual DbSet<DonationOccurence> DonationOccurences { get; set; }
        public virtual DbSet<DonationProfile> DonationProfiles { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<DonorsProfile> DonorsProfiles { get; set; }
        public virtual DbSet<EmerageContact> EmerageContacts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeSchedule> EmployeeSchedules { get; set; }
        public virtual DbSet<EmployeeStatu> EmployeeStatus { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<GetHelp> GetHelps { get; set; }
        public virtual DbSet<GiftItem> GiftItems { get; set; }
        public virtual DbSet<GiftType> GiftTypes { get; set; }
        public virtual DbSet<HospitalEvent> HospitalEvents { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<JobApplicant> JobApplicants { get; set; }
        public virtual DbSet<JobPosting> JobPostings { get; set; }
        public virtual DbSet<Navigation> Navigations { get; set; }
        public virtual DbSet<OnCall> OnCalls { get; set; }
        public virtual DbSet<OrderPlaced> OrderPlaceds { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientsRoom> PatientsRooms { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<SubNavigation> SubNavigations { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VolunteerApplicant> VolunteerApplicants { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
        public virtual DbSet<WhatToBring> WhatToBrings { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<OrderPlaced1> OrderPlaceds1 { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
    }
}
