//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubNavigation
    {
        public int subNavId { get; set; }
        public int navId { get; set; }
        public string subNavTitle { get; set; }
        public string subNavUrl { get; set; }
        public int employeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Navigation Navigation { get; set; }
    }
}
