//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerApplicant
    {
        public int volunteerApplicantsId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string postal { get; set; }
        public System.DateTime birthDate { get; set; }
        public System.DateTime startingDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string available { get; set; }
        public string decision { get; set; }
    }
}
