//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Volunteer()
        {
            this.OnCalls = new HashSet<OnCall>();
        }
    
        public int volunteerId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string position { get; set; }
        public int departmentId { get; set; }
        public Nullable<int> contactId { get; set; }
        public Nullable<int> addressId { get; set; }
        public Nullable<int> emerageContactID { get; set; }
        public System.DateTime birthDate { get; set; }
        public string schedule { get; set; }
        public string tasks { get; set; }
        public byte onCall { get; set; }
        public Nullable<int> insuranceId { get; set; }
    
        public virtual Addresses1 Addresses1 { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual EmerageContact EmerageContact { get; set; }
        public virtual Insurance Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnCall> OnCalls { get; set; }
    }
}
