//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhatToBring
    {
        public int whatToBringId { get; set; }
        public string itemName { get; set; }
        public Nullable<int> departmentsId { get; set; }
        public string departmentName { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
